# ============================================================
# LAB CONFIGURATION — UPI Fresh Install Lab
# OCP 4.20 + Isovalent Networking for Kubernetes 1.18 + Timescape
# Single source of truth for all env vars in this lab.
# Usage: source /root/tools-upi-install/lab-config.sh
#
# Coexists with /root/tools-upi-migrate (the OVN→Cilium migration lab on
# the same 192.168.39.0/24, different IP block).
# ============================================================

# --- PATH ---
export PATH=/usr/local/bin:$PATH

# --- OCP Cluster ---
export OCP_VERSION=4.20.24                                  # « CHANGE » Target OCP z-stream version (latest 4.20.z at time of writing)
export CLUSTER_NAME=ocp-install                             # « CHANGE » Cluster name (part of FQDNs)
export BASE_DOMAIN=md.prglab.local                          # « CHANGE » Base DNS domain (same lab DNS as migration cluster)

# --- Install working directory ---
export INSTALL_DIR=/root/ocp-upi-install                    # Distinct from /root/ocp-upi-migrate

# --- Network ---
# Shared bastion at 192.168.39.20 — same /24 as the migration cluster.
# Different IP block prevents collisions; HAProxy listens on .30 for this cluster.
export NODE_NETWORK=192.168.39.0/24
export NODE_GATEWAY=192.168.39.1                            # « CHANGE » Default gateway (same lab gateway)
export BASTION_IP=192.168.39.20                             # Shared bastion (Nexus + dnsmasq + httpd live here)
export DNS_SERVER=192.168.33.10                             # Existing lab DNS — needs new zone records for ocp-install
export API_VIP=192.168.39.30                                # NEW: distinct HAProxy frontend for this cluster's API
export INGRESS_VIP=192.168.39.30                            # NEW: same address fronts Ingress for this cluster
export POD_CIDR=10.244.0.0/14                               # « CHANGE-IF-NEEDED » Pod CIDR — must NOT overlap migration cluster (10.128.0.0/14)
export POD_HOST_PREFIX=23                                   # Each node gets a /23 subnet
export SERVICE_CIDR=172.31.0.0/16                           # « CHANGE-IF-NEEDED » Service CIDR — must NOT overlap migration cluster (172.30.0.0/16)

# --- Node IPs (.29 bootstrap, .31-.33 masters, .35-.37 workers; .34/.38 reserved) ---
export BOOTSTRAP_IP=192.168.39.29                           # Temporary bootstrap node
export MASTER0_IP=192.168.39.31
export MASTER1_IP=192.168.39.32
export MASTER2_IP=192.168.39.33
export WORKER0_IP=192.168.39.35
export WORKER1_IP=192.168.39.36
export WORKER2_IP=192.168.39.37
# .34 (master-i-3) and .38 (worker-i-3) reserved for future expansion

# --- NIC name on RHCOS nodes (verify with `ip link` after first boot) ---
export PRIMARY_NIC=ens192                                   # vSphere default for the primary vmxnet3 NIC

# --- Artifactory (Nexus pull-through) — REUSED from the migration lab bastion ---
# The migration cluster's Nexus already proxies: quay.io, registry.redhat.io,
# registry.connect.redhat.com, docker.io (authenticated), quay.io/isovalent,
# registry.k8s.io. No need to stand up a second Nexus.
export ARTIFACTORY_HOST=artifactory.ocp-migrate.md.prglab.local  # Shared Nexus FQDN (cert is for ocp-migrate)
export ARTIFACTORY_PORT=8443
export ARTIFACTORY_URL="https://${ARTIFACTORY_HOST}:${ARTIFACTORY_PORT}"
export ARTIFACTORY_USER=admin
export ARTIFACTORY_PASS=Passw0rd.
export ARTIFACTORY_OCP_REPO=ocp-images                      # Same group repo as migration cluster
export ARTIFACTORY_DATA_DIR=/home/nexus-data

# Docker Hub PAT — same as migration lab; remote-dockerhub already authenticated
export DOCKERHUB_USER=                                      # « CHANGE » Docker Hub username for the PAT (external)
export DOCKERHUB_PASS=                                      # « CHANGE » Docker Hub Personal Access Token (external)

# --- Red Hat Pull Secret ---
export PULL_SECRET_FILE=/root/pull-secret.json              # Same RH pull secret as migration lab
export PULL_SECRET_ART_FILE=/root/pull-secret-with-art.json # Already generated by the migration lab's setup-artifactory.sh
export SSH_KEY_FILE=/root/.ssh/id_rsa.pub                   # Same SSH key

# --- Isovalent Enterprise — IEP 1.18 (latest 4.20-certified per RH 5436171) ---
# Compatibility matrix: https://access.redhat.com/articles/5436171
# 1.18 is certified for OCP 4.20 with Net, Virt, Mesh, HCP tests passed.
# Tarball naming + hosting paths (observed at docs.isovalent.com):
#   - 1.18.x: clife-v<X.Y.Z>.tar.gz     under /v25.11/public/clife/
#   - 1.17.x: clife-v<X.Y.Z>.tar.gz     under /v1.17/public/clife/
export CILIUM_EE_VERSION=1.18.9                             # « CHANGE » Latest 1.18.z — verify at docs.cisco.com/iep
export CLIFE_DOCS_PATH=v25.11                               # 1.18 lives under v25.11; 1.17 lives under v1.17
export CEE_SUFFIX=                                          # empty for 1.17+; cee.N for 1.16 and earlier
if [ -n "${CEE_SUFFIX}" ]; then
  export CLIFE_TARBALL="clife-v${CILIUM_EE_VERSION}-${CEE_SUFFIX}.tar.gz"
else
  export CLIFE_TARBALL="clife-v${CILIUM_EE_VERSION}.tar.gz"
fi
export CLIFE_URL="https://docs.isovalent.com/${CLIFE_DOCS_PATH}/public/clife/${CLIFE_TARBALL}"
export CLIFE_DIR="${INSTALL_DIR}/clife"

# Cilium CIDR for FRESH INSTALL — Cilium IS the only CNI here, no need to dodge OVN.
# Must NOT overlap POD_CIDR though (we set them equal; Cilium uses POD_CIDR via IPAM cluster-pool).
# In fresh-install mode Cilium IPAM and OCP networking are the same range.
export CILIUM_CLUSTER_CIDR=${POD_CIDR}                      # Same as POD_CIDR for fresh install
export CILIUM_HOST_PREFIX=${POD_HOST_PREFIX}

# --- Hubble Timescape (deployed inline in Section 9 of the install guide) ---
export TIMESCAPE_VERSION=v1.18.9                            # « CHANGE » match TIMESCAPE chart minor with IEP minor (chart 1.18.x = Timescape 1.18.x)
export CLICKHOUSE_OPERATOR_VERSION=0.23.5                   # « CHANGE » https://docs.altinity.com/clickhouse-operator
export METRICS_EXPORTER_TAG=0.27.1                          # « CHANGE » altinity/metrics-exporter has its OWN versioning — see lessons-learned

# --- vSphere ---
export VCENTER_HOST=                                        # « CHANGE » vCenter FQDN, e.g. prg-vcenter.cisco.com (external)
export VCENTER_USER=                                        # « CHANGE » vCenter username (external)
export VCENTER_PASS=                                        # « CHANGE » vCenter password (external)
export VCENTER_DATACENTER=PRG-LAB                           # « CHANGE »
export VCENTER_DATASTORE="PRG-LAB-HX DS1"                   # « CHANGE »
export VCENTER_FOLDER="/PRG-LAB/vm/mdivis/OCP-Install"      # « CHANGE » Separate folder from migration lab (which uses OCP-Migrate)
export VCENTER_HOST_TARGET=                                 # « CHANGE » ESXi host, e.g. prg-lab-hx3.cisco.com (external)
export VCENTER_RESOURCE_POOL="/PRG-LAB/host/PRG-LAB-HX/Resources" # « CHANGE »
export VCENTER_NETWORK="PRG-LAB/PRG-DC-39"                  # Same DVS port-group as migration cluster — both clusters live on .39/24

export GOVC_URL="https://${VCENTER_HOST}:443"
export GOVC_USERNAME="${VCENTER_USER}"
export GOVC_PASSWORD="${VCENTER_PASS}"
export GOVC_INSECURE=1
export GOVC_DATASTORE="${VCENTER_DATASTORE}"

# --- VM names (suffix -i- to distinguish from migration lab's -m-) ---
export VM_BOOTSTRAP="bootstrap-i (install)"
export VM_MASTER0="master-i-0 (install)"
export VM_MASTER1="master-i-1 (install)"
export VM_MASTER2="master-i-2 (install)"
export VM_WORKER0="worker-i-0 (install)"
export VM_WORKER1="worker-i-1 (install)"
export VM_WORKER2="worker-i-2 (install)"

# --- Derived values (do not edit) ---
export KUBECONFIG=${INSTALL_DIR}/auth/kubeconfig
export K8S_API_HOST="api-int.${CLUSTER_NAME}.${BASE_DOMAIN}"
export K8S_API_PORT=6443
if [ -n "${CEE_SUFFIX}" ]; then
  export CLIFE_VERSION="v${CILIUM_EE_VERSION}-${CEE_SUFFIX}"
else
  export CLIFE_VERSION="v${CILIUM_EE_VERSION}"
fi

# --- NFS export for Timescape PVCs (separate from migration cluster's export) ---
export NFS_EXPORT_PATH=/srv/nfs/openshift-install           # Distinct from /srv/nfs/openshift (migration)
export NFS_STORAGE_CLASS=nfs-storage-install                # Distinct SC name; both clusters can coexist in cluster-storage list
