# ============================================================
# LAB CONFIGURATION — UPI Migration Lab
# OCP 4.16 with OVN-Kubernetes → Isovalent Enterprise Platform
# Single source of truth for all env vars in this lab.
# Usage: source /root/tools-upi-migrate/lab-config.sh
# ============================================================

# --- PATH ---
export PATH=/usr/local/bin:$PATH

# --- OCP Cluster ---
export OCP_VERSION=4.16.36                                  # « CHANGE » Target OCP z-stream version
export CLUSTER_NAME=ocp-migrate                             # « CHANGE » Cluster name (part of FQDNs)
export BASE_DOMAIN=md.prglab.local                          # « CHANGE » Base DNS domain

# --- Install working directory ---
export INSTALL_DIR=/root/ocp-upi-migrate

# --- Network ---
export NODE_NETWORK=192.168.39.0/24                         # Node/machine network CIDR
export NODE_GATEWAY=192.168.39.1                            # « CHANGE » Default gateway
export BASTION_IP=192.168.39.20                             # Bastion host IP (this machine)
export DNS_SERVER=192.168.33.10                             # Existing lab DNS server
export API_VIP=192.168.39.20                                # HAProxy frontend for API (port 6443/22623) — bastion
export INGRESS_VIP=192.168.39.20                            # HAProxy frontend for Ingress (port 80/443) — bastion
export POD_CIDR=10.128.0.0/14                               # OCP default pod CIDR (OVN-Kubernetes)
export POD_HOST_PREFIX=23                                   # Each node gets a /23 subnet
export SERVICE_CIDR=172.30.0.0/16                           # Service network CIDR

# --- Node IPs ---
export BOOTSTRAP_IP=192.168.39.19                           # Temporary bootstrap node
export MASTER0_IP=192.168.39.21
export MASTER1_IP=192.168.39.22
export MASTER2_IP=192.168.39.23
export WORKER0_IP=192.168.39.25
export WORKER1_IP=192.168.39.26
export WORKER2_IP=192.168.39.27
# .24 (master-m-3) and .28 (worker-m-3) reserved for future expansion

# --- NIC name on RHCOS nodes (verify with `ip link` after first boot) ---
export PRIMARY_NIC=ens192                                   # « CHANGE »

# --- Artifactory ---
export ARTIFACTORY_HOST=artifactory.${CLUSTER_NAME}.${BASE_DOMAIN}
export ARTIFACTORY_PORT=8443
export ARTIFACTORY_URL="https://${ARTIFACTORY_HOST}:${ARTIFACTORY_PORT}"
export ARTIFACTORY_USER=admin                               # « CHANGE »
export ARTIFACTORY_PASS=Passw0rd.                           # « CHANGE »
export ARTIFACTORY_OCP_REPO=ocp-images                     # Nexus group repo name
export ARTIFACTORY_DATA_DIR=/home/nexus-data               # Nexus data directory (was Artifactory)

# --- Red Hat Pull Secret ---
export PULL_SECRET_FILE=/root/pull-secret.json              # « CHANGE » Download from console.redhat.com
export PULL_SECRET_ART_FILE=/root/pull-secret-with-art.json # Generated by setup-artifactory.sh
export SSH_KEY_FILE=/root/.ssh/id_rsa.pub                   # « CHANGE »

# --- Isovalent Enterprise (post-migration) ---
# CLife tarball naming + hosting paths (observed at docs.isovalent.com):
#   - 1.18.x: clife-v<X.Y.Z>.tar.gz     under /v25.11/public/clife/
#   - 1.17.x: clife-v<X.Y.Z>.tar.gz     under /v1.17/public/clife/
#   - 1.16 and earlier: clife-v<X.Y.Z>-cee.N.tar.gz (legacy -cee.N suffix)
# Set CILIUM_EE_VERSION (e.g. 1.17.15), CLIFE_DOCS_PATH (e.g. v1.17 or v25.11),
# and CEE_SUFFIX (empty for 1.17+, "cee.N" for 1.16 and earlier).
export CILIUM_EE_VERSION=1.17.15                            # « CHANGE » Certified IEP version for your OCP minor
export CLIFE_DOCS_PATH=v1.17                                # « CHANGE » v1.17 for 1.17.x, v25.11 for 1.18.x
export CEE_SUFFIX=                                          # « CHANGE » empty for 1.17+; cee.N for 1.16 and earlier
if [ -n "${CEE_SUFFIX}" ]; then
  export CLIFE_TARBALL="clife-v${CILIUM_EE_VERSION}-${CEE_SUFFIX}.tar.gz"
else
  export CLIFE_TARBALL="clife-v${CILIUM_EE_VERSION}.tar.gz"
fi
export CLIFE_URL="https://docs.isovalent.com/${CLIFE_DOCS_PATH}/public/clife/${CLIFE_TARBALL}"
export CLIFE_DIR="${INSTALL_DIR}/clife"

# Cilium CIDR — MUST NOT overlap with POD_CIDR (OVN-Kubernetes uses 10.128.0.0/14)
export CILIUM_CLUSTER_CIDR=10.253.0.0/16
export CILIUM_HOST_PREFIX=24

# --- vSphere ---
export VCENTER_HOST=***               # « CHANGE »
export VCENTER_USER=***                               # « CHANGE »
export VCENTER_PASS=***                              # « CHANGE »
export VCENTER_DATACENTER=PRG-LAB                           # « CHANGE »
export VCENTER_DATASTORE="PRG-LAB-HX DS1"                   # « CHANGE »
export VCENTER_FOLDER="/PRG-LAB/vm/mdivis/OCP-Migrate"      # « CHANGE » separate folder from existing lab
export VCENTER_HOST_TARGET=***           # « CHANGE » ESXi host
export VCENTER_RESOURCE_POOL="/PRG-LAB/host/PRG-LAB-HX/Resources" # « CHANGE »
export VCENTER_NETWORK="PRG-LAB/PRG-DC-39"                  # « CHANGE » DVS-relative port group path (under /<DC>/network/) for 192.168.39.0/24

export GOVC_URL="https://${VCENTER_HOST}:443"
export GOVC_USERNAME="${VCENTER_USER}"
export GOVC_PASSWORD="${VCENTER_PASS}"
export GOVC_INSECURE=1
export GOVC_DATASTORE="${VCENTER_DATASTORE}"

# --- Derived values (do not edit) ---
export KUBECONFIG=${INSTALL_DIR}/auth/kubeconfig
export K8S_API_HOST="api-int.${CLUSTER_NAME}.${BASE_DOMAIN}"
export K8S_API_PORT=6443
if [ -n "${CEE_SUFFIX}" ]; then
  export CLIFE_VERSION="v${CILIUM_EE_VERSION}-${CEE_SUFFIX}"
else
  export CLIFE_VERSION="v${CILIUM_EE_VERSION}"
fi
